[2024-03-06T16:54:06.273+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00/task_id=create_table_user permission to 509
[2024-03-06T16:54:06.275+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00 permission to 509
[2024-03-06T16:54:06.277+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T16:54:06.279+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T16:54:06.281+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T16:54:06.283+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T16:54:06.283+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T16:54:06.343+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00/task_id=create_table_user permission to 509
[2024-03-06T16:54:06.344+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00 permission to 509
[2024-03-06T16:54:06.346+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T16:54:06.348+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T16:54:06.349+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T16:54:06.351+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T16:54:06.352+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T16:54:06.389+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T11:51:59.569526+00:00 [queued]>
[2024-03-06T16:54:06.408+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T11:51:59.569526+00:00 [queued]>
[2024-03-06T16:54:06.408+0500] {taskinstance.py:2193} INFO - Starting attempt 2 of 6
[2024-03-06T16:54:06.449+0500] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): create_table_user> on 2024-03-06 11:51:59.569526+00:00
[2024-03-06T16:54:06.452+0500] {standard_task_runner.py:60} INFO - Started process 11356 to run task
[2024-03-06T16:54:06.455+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_operator_dag_v_1', 'create_table_user', 'manual__2024-03-06T11:51:59.569526+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator_dag.py', '--cfg-path', '/tmp/tmpqd1llbwk']
[2024-03-06T16:54:06.457+0500] {standard_task_runner.py:88} INFO - Job 56: Subtask create_table_user
[2024-03-06T16:54:06.543+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00/task_id=create_table_user permission to 509
[2024-03-06T16:54:06.545+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00 permission to 509
[2024-03-06T16:54:06.547+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T16:54:06.548+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T16:54:06.550+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T16:54:06.551+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T16:54:06.552+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T16:54:06.554+0500] {task_command.py:423} INFO - Running <TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T11:51:59.569526+00:00 [running]> on host DESKTOP-QMFTH9M.
[2024-03-06T16:54:06.684+0500] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naeem' AIRFLOW_CTX_DAG_ID='postgres_operator_dag_v_1' AIRFLOW_CTX_TASK_ID='create_table_user' AIRFLOW_CTX_EXECUTION_DATE='2024-03-06T11:51:59.569526+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-06T11:51:59.569526+00:00'
[2024-03-06T16:54:06.685+0500] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
            user_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            age VARCHAR NOT NULL,
            dob DATE NOT NULL);
          
[2024-03-06T16:54:06.700+0500] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2024-03-06T16:54:06.728+0500] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2024-03-06T16:54:06.730+0500] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/naeem/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.28.25.178", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-03-06T16:54:06.743+0500] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_operator_dag_v_1, task_id=create_table_user, execution_date=20240306T115159, start_date=20240306T115406, end_date=20240306T115406
[2024-03-06T16:54:06.783+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 56 for task create_table_user (connection to server at "172.28.25.178", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 11356)
[2024-03-06T16:54:06.792+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T16:54:06.816+0500] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
