[2024-03-06T16:58:12.035+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00/task_id=create_table_user permission to 509
[2024-03-06T16:58:12.038+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00 permission to 509
[2024-03-06T16:58:12.041+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T16:58:12.044+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T16:58:12.046+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T16:58:12.048+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T16:58:12.049+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T16:58:12.137+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00/task_id=create_table_user permission to 509
[2024-03-06T16:58:12.139+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00 permission to 509
[2024-03-06T16:58:12.141+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T16:58:12.143+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T16:58:12.145+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T16:58:12.148+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T16:58:12.150+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T16:58:12.205+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T11:51:59.569526+00:00 [queued]>
[2024-03-06T16:58:12.233+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T11:51:59.569526+00:00 [queued]>
[2024-03-06T16:58:12.234+0500] {taskinstance.py:2193} INFO - Starting attempt 4 of 6
[2024-03-06T16:58:12.351+0500] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): create_table_user> on 2024-03-06 11:51:59.569526+00:00
[2024-03-06T16:58:12.355+0500] {standard_task_runner.py:60} INFO - Started process 11628 to run task
[2024-03-06T16:58:12.360+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_operator_dag_v_1', 'create_table_user', 'manual__2024-03-06T11:51:59.569526+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator_dag.py', '--cfg-path', '/tmp/tmpobp_lrsr']
[2024-03-06T16:58:12.364+0500] {standard_task_runner.py:88} INFO - Job 58: Subtask create_table_user
[2024-03-06T16:58:12.483+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00/task_id=create_table_user permission to 509
[2024-03-06T16:58:12.485+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T11:51:59.569526+00:00 permission to 509
[2024-03-06T16:58:12.487+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T16:58:12.494+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T16:58:12.497+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T16:58:12.499+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T16:58:12.500+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T16:58:12.503+0500] {task_command.py:423} INFO - Running <TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T11:51:59.569526+00:00 [running]> on host DESKTOP-QMFTH9M.
[2024-03-06T16:58:12.664+0500] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naeem' AIRFLOW_CTX_DAG_ID='postgres_operator_dag_v_1' AIRFLOW_CTX_TASK_ID='create_table_user' AIRFLOW_CTX_EXECUTION_DATE='2024-03-06T11:51:59.569526+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-06T11:51:59.569526+00:00'
[2024-03-06T16:58:12.664+0500] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
            user_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            age VARCHAR NOT NULL,
            dob DATE NOT NULL);
          
[2024-03-06T16:58:12.684+0500] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2024-03-06T16:58:12.718+0500] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2024-03-06T16:58:12.720+0500] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/naeem/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.28.25.178", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-03-06T16:58:12.736+0500] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_operator_dag_v_1, task_id=create_table_user, execution_date=20240306T115159, start_date=20240306T115812, end_date=20240306T115812
[2024-03-06T16:58:12.792+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 58 for task create_table_user (connection to server at "172.28.25.178", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 11628)
[2024-03-06T16:58:12.807+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T16:58:12.838+0500] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
