[2024-03-06T15:40:19.856+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00/task_id=create_table_user permission to 509
[2024-03-06T15:40:19.859+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00 permission to 509
[2024-03-06T15:40:19.861+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T15:40:19.863+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T15:40:19.865+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T15:40:19.867+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T15:40:19.868+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T15:40:19.950+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00/task_id=create_table_user permission to 509
[2024-03-06T15:40:19.952+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00 permission to 509
[2024-03-06T15:40:19.954+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T15:40:19.955+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T15:40:19.957+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T15:40:19.959+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T15:40:19.960+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T15:40:20.003+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T10:40:15.407792+00:00 [queued]>
[2024-03-06T15:40:20.027+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T10:40:15.407792+00:00 [queued]>
[2024-03-06T15:40:20.028+0500] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-03-06T15:40:20.098+0500] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): create_table_user> on 2024-03-06 10:40:15.407792+00:00
[2024-03-06T15:40:20.102+0500] {standard_task_runner.py:60} INFO - Started process 5650 to run task
[2024-03-06T15:40:20.108+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_operator_dag_v_1', 'create_table_user', 'manual__2024-03-06T10:40:15.407792+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator_dag.py', '--cfg-path', '/tmp/tmpejfzsgnn']
[2024-03-06T15:40:20.111+0500] {standard_task_runner.py:88} INFO - Job 31: Subtask create_table_user
[2024-03-06T15:40:20.261+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00/task_id=create_table_user permission to 509
[2024-03-06T15:40:20.264+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00 permission to 509
[2024-03-06T15:40:20.266+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T15:40:20.268+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T15:40:20.270+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T15:40:20.272+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T15:40:20.275+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T15:40:20.278+0500] {task_command.py:423} INFO - Running <TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T10:40:15.407792+00:00 [running]> on host DESKTOP-QMFTH9M.
[2024-03-06T15:40:20.477+0500] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naeem' AIRFLOW_CTX_DAG_ID='postgres_operator_dag_v_1' AIRFLOW_CTX_TASK_ID='create_table_user' AIRFLOW_CTX_EXECUTION_DATE='2024-03-06T10:40:15.407792+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-06T10:40:15.407792+00:00'
[2024-03-06T15:40:20.479+0500] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
            user_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            age VARCHAR NOT NULL,
            dob DATE NOT NULL);
          
[2024-03-06T15:40:20.501+0500] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2024-03-06T15:40:20.545+0500] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2024-03-06T15:40:20.547+0500] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/naeem/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-03-06T15:40:20.565+0500] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_operator_dag_v_1, task_id=create_table_user, execution_date=20240306T104015, start_date=20240306T104020, end_date=20240306T104020
[2024-03-06T15:40:20.621+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task create_table_user (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 5650)
[2024-03-06T15:40:20.641+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T15:40:20.673+0500] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
