[2024-03-06T15:50:35.598+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00/task_id=create_table_user permission to 509
[2024-03-06T15:50:35.600+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00 permission to 509
[2024-03-06T15:50:35.603+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T15:50:35.605+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T15:50:35.609+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T15:50:35.611+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T15:50:35.613+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T15:50:35.694+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00/task_id=create_table_user permission to 509
[2024-03-06T15:50:35.697+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00 permission to 509
[2024-03-06T15:50:35.700+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T15:50:35.702+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T15:50:35.704+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T15:50:35.706+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T15:50:35.707+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T15:50:35.755+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T10:40:15.407792+00:00 [queued]>
[2024-03-06T15:50:35.780+0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T10:40:15.407792+00:00 [queued]>
[2024-03-06T15:50:35.781+0500] {taskinstance.py:2193} INFO - Starting attempt 6 of 6
[2024-03-06T15:50:35.852+0500] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): create_table_user> on 2024-03-06 10:40:15.407792+00:00
[2024-03-06T15:50:35.855+0500] {standard_task_runner.py:60} INFO - Started process 6714 to run task
[2024-03-06T15:50:35.860+0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_operator_dag_v_1', 'create_table_user', 'manual__2024-03-06T10:40:15.407792+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/postgres_operator_dag.py', '--cfg-path', '/tmp/tmphluopwx1']
[2024-03-06T15:50:35.863+0500] {standard_task_runner.py:88} INFO - Job 36: Subtask create_table_user
[2024-03-06T15:50:35.995+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00/task_id=create_table_user permission to 509
[2024-03-06T15:50:35.997+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1/run_id=manual__2024-03-06T10:40:15.407792+00:00 permission to 509
[2024-03-06T15:50:35.999+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs/dag_id=postgres_operator_dag_v_1 permission to 509
[2024-03-06T15:50:36.001+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial/logs permission to 509
[2024-03-06T15:50:36.004+0500] {logging_mixin.py:188} INFO - Changing /mnt/c/airflow_tutorial permission to 509
[2024-03-06T15:50:36.006+0500] {logging_mixin.py:188} INFO - Changing /mnt/c permission to 509
[2024-03-06T15:50:36.008+0500] {logging_mixin.py:188} INFO - Failed to change /mnt/c permission to 509: [Errno 13] Permission denied: '/mnt/c'
[2024-03-06T15:50:36.011+0500] {task_command.py:423} INFO - Running <TaskInstance: postgres_operator_dag_v_1.create_table_user manual__2024-03-06T10:40:15.407792+00:00 [running]> on host DESKTOP-QMFTH9M.
[2024-03-06T15:50:36.181+0500] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naeem' AIRFLOW_CTX_DAG_ID='postgres_operator_dag_v_1' AIRFLOW_CTX_TASK_ID='create_table_user' AIRFLOW_CTX_EXECUTION_DATE='2024-03-06T10:40:15.407792+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-06T10:40:15.407792+00:00'
[2024-03-06T15:50:36.183+0500] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
            user_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            age VARCHAR NOT NULL,
            dob DATE NOT NULL);
          
[2024-03-06T15:50:36.203+0500] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2024-03-06T15:50:36.246+0500] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2024-03-06T15:50:36.248+0500] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/naeem/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/naeem/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-03-06T15:50:36.263+0500] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=postgres_operator_dag_v_1, task_id=create_table_user, execution_date=20240306T104015, start_date=20240306T105035, end_date=20240306T105036
[2024-03-06T15:50:36.322+0500] {standard_task_runner.py:107} ERROR - Failed to execute job 36 for task create_table_user (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 6714)
[2024-03-06T15:50:36.362+0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T15:50:36.396+0500] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
